# Generated by Django 5.2 on 2025-08-26 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ementas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ementa',
            name='sigiloso',
            field=models.BooleanField(default=False, help_text='Marque se esta ementa contém informações sigilosas', verbose_name='Sigiloso'),
        ),
        migrations.AddField(
            model_name='ementa',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ementas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
