# Generated by Django 5.2 on 2025-08-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ementas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ementa',
            name='ementa',
            field=models.TextField(blank=True, help_text='Resumo do ato normativo para facilitar a pesquisa', verbose_name='Ementa (Resumo)'),
        ),
        migrations.AddField(
            model_name='ementa',
            name='situacao',
            field=models.CharField(choices=[('em_vigor', 'Em Vigor'), ('revogada', 'Revogada'), ('cancelada', 'Cancelada')], default='em_vigor', max_length=20, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='ementa',
            name='tipo_ato_normativo',
            field=models.CharField(choices=[('portaria', 'Portaria'), ('decisao_plenaria', 'Decisão Plenária'), ('ato_administrativo', 'Ato Administrativo')], default='portaria', max_length=20, verbose_name='Tipo de Ato Normativo'),
        ),
    ]
